//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчетный лист.
    /// </summary>
    // *** Start programmer edit section *** (РасчетныйЛист CustomAttributes)

    // *** End programmer edit section *** (РасчетныйЛист CustomAttributes)
    [AutoAltered()]
    [Caption("Расчетный лист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетныйЛистE", new string[] {
            "КодДок as \'Код документа\'",
            "Дата as \'Дата\'",
            "СотрудникиКу.Фио as \'ФИО сотрудника\'",
            "СотрудникиКу.Должности.Наименование as \'Должность\'"}, Hidden=new string[] {
            "СотрудникиКу.Фио"})]
    [AssociatedDetailViewAttribute("РасчетныйЛистE", "СоставРасчета", "СоставРасчетаE", true, "", "Состав расчета", true, new string[] {
            ""})]
    [View("РасчетныйЛистL", new string[] {
            "КодДок as \'Код документа\'",
            "Дата as \'Дата\'",
            "СотрудникиКу.Фио as \'ФИО\'",
            "СотрудникиКу.Должности.Наименование as \'Должность\'"})]
    public class РасчетныйЛист : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодДок;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.VUA.СотрудникиКу fСотрудникиКу;
        
        private IIS.VUA.DetailArrayOfСоставРасчета fСоставРасчета;
        
        // *** Start programmer edit section *** (РасчетныйЛист CustomMembers)

        // *** End programmer edit section *** (РасчетныйЛист CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.Дата CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Get start)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Get end)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Set start)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Set end)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодДок.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.КодДок CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.КодДок CustomAttributes)
        public virtual int КодДок
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.КодДок Get start)

                // *** End programmer edit section *** (РасчетныйЛист.КодДок Get start)
                int result = this.fКодДок;
                // *** Start programmer edit section *** (РасчетныйЛист.КодДок Get end)

                // *** End programmer edit section *** (РасчетныйЛист.КодДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.КодДок Set start)

                // *** End programmer edit section *** (РасчетныйЛист.КодДок Set start)
                this.fКодДок = value;
                // *** Start programmer edit section *** (РасчетныйЛист.КодДок Set end)

                // *** End programmer edit section *** (РасчетныйЛист.КодДок Set end)
            }
        }
        
        /// <summary>
        /// Расчетный лист.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.СотрудникиКу CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.СотрудникиКу CustomAttributes)
        [PropertyStorage(new string[] {
                "СотрудникиКу"})]
        [NotNull()]
        public virtual IIS.VUA.СотрудникиКу СотрудникиКу
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.СотрудникиКу Get start)

                // *** End programmer edit section *** (РасчетныйЛист.СотрудникиКу Get start)
                IIS.VUA.СотрудникиКу result = this.fСотрудникиКу;
                // *** Start programmer edit section *** (РасчетныйЛист.СотрудникиКу Get end)

                // *** End programmer edit section *** (РасчетныйЛист.СотрудникиКу Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.СотрудникиКу Set start)

                // *** End programmer edit section *** (РасчетныйЛист.СотрудникиКу Set start)
                this.fСотрудникиКу = value;
                // *** Start programmer edit section *** (РасчетныйЛист.СотрудникиКу Set end)

                // *** End programmer edit section *** (РасчетныйЛист.СотрудникиКу Set end)
            }
        }
        
        /// <summary>
        /// Расчетный лист.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета CustomAttributes)
        public virtual IIS.VUA.DetailArrayOfСоставРасчета СоставРасчета
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Get start)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Get start)
                if ((this.fСоставРасчета == null))
                {
                    this.fСоставРасчета = new IIS.VUA.DetailArrayOfСоставРасчета(this);
                }
                IIS.VUA.DetailArrayOfСоставРасчета result = this.fСоставРасчета;
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Get end)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Set start)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Set start)
                this.fСоставРасчета = value;
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Set end)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетныйЛистE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетныйЛистE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетныйЛистE", typeof(IIS.VUA.РасчетныйЛист));
                }
            }
            
            /// <summary>
            /// "РасчетныйЛистL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетныйЛистL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетныйЛистL", typeof(IIS.VUA.РасчетныйЛист));
                }
            }
        }
    }
}
