//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав расчета.
    /// </summary>
    // *** Start programmer edit section *** (СоставРасчета CustomAttributes)

    // *** End programmer edit section *** (СоставРасчета CustomAttributes)
    [AutoAltered()]
    [Caption("Состав расчета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставРасчетаE", new string[] {
            "Тип as \'Тип\'",
            "Оклад as \'Оклад\'",
            "Ндфл as \'НДФЛ\'"})]
    public class СоставРасчета : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.VUA.Тип fТип;
        
        private double fОклад;
        
        private double fНдфл;
        
        private IIS.VUA.РасчетныйЛист fРасчетныйЛист;
        
        // *** Start programmer edit section *** (СоставРасчета CustomMembers)

        // *** End programmer edit section *** (СоставРасчета CustomMembers)

        
        /// <summary>
        /// Ндфл.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Ндфл CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Ндфл CustomAttributes)
        public virtual double Ндфл
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Get start)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Get start)
                double result = this.fНдфл;
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Get end)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Set start)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Set start)
                this.fНдфл = value;
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Set end)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Оклад CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Оклад CustomAttributes)
        public virtual double Оклад
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Оклад Get start)

                // *** End programmer edit section *** (СоставРасчета.Оклад Get start)
                double result = this.fОклад;
                // *** Start programmer edit section *** (СоставРасчета.Оклад Get end)

                // *** End programmer edit section *** (СоставРасчета.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Оклад Set start)

                // *** End programmer edit section *** (СоставРасчета.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (СоставРасчета.Оклад Set end)

                // *** End programmer edit section *** (СоставРасчета.Оклад Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Тип CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Тип CustomAttributes)
        public virtual IIS.VUA.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Тип Get start)

                // *** End programmer edit section *** (СоставРасчета.Тип Get start)
                IIS.VUA.Тип result = this.fТип;
                // *** Start programmer edit section *** (СоставРасчета.Тип Get end)

                // *** End programmer edit section *** (СоставРасчета.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Тип Set start)

                // *** End programmer edit section *** (СоставРасчета.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (СоставРасчета.Тип Set end)

                // *** End programmer edit section *** (СоставРасчета.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.VUA.РасчетныйЛист.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетныйЛист"})]
        public virtual IIS.VUA.РасчетныйЛист РасчетныйЛист
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Get start)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Get start)
                IIS.VUA.РасчетныйЛист result = this.fРасчетныйЛист;
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Get end)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Set start)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Set start)
                this.fРасчетныйЛист = value;
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Set end)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставРасчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставРасчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставРасчетаE", typeof(IIS.VUA.СоставРасчета));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставРасчета.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставРасчета CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставРасчета CustomAttributes)
    public class DetailArrayOfСоставРасчета : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.VUA.DetailArrayOfСоставРасчета members)

        // *** End programmer edit section *** (IIS.VUA.DetailArrayOfСоставРасчета members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставРасчета by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставРасчета.
        /// </summary>
        public DetailArrayOfСоставРасчета(IIS.VUA.РасчетныйЛист fРасчетныйЛист) : 
                base(typeof(СоставРасчета), ((ICSSoft.STORMNET.DataObject)(fРасчетныйЛист)))
        {
        }
        
        public IIS.VUA.СоставРасчета this[int index]
        {
            get
            {
                return ((IIS.VUA.СоставРасчета)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.VUA.СоставРасчета dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
