//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники ку.
    /// </summary>
    // *** Start programmer edit section *** (СотрудникиКу CustomAttributes)

    // *** End programmer edit section *** (СотрудникиКу CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудники")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиКуE", new string[] {
            "Код as \'Код\'",
            "Фио as \'Фио\'",
            "Должности.Наименование as \'Должность\'"}, Hidden=new string[] {
            "Должности.Наименование"})]
    [View("СотрудникиКуL", new string[] {
            "Код as \'Код\'",
            "Фио as \'Фио\'",
            "Должности.Наименование as \'Должность\'"})]
    public class СотрудникиКу : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fФио;
        
        private IIS.VUA.Должности fДолжности;
        
        // *** Start programmer edit section *** (СотрудникиКу CustomMembers)

        // *** End programmer edit section *** (СотрудникиКу CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (СотрудникиКу.Код CustomAttributes)

        // *** End programmer edit section *** (СотрудникиКу.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (СотрудникиКу.Код Get start)

                // *** End programmer edit section *** (СотрудникиКу.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (СотрудникиКу.Код Get end)

                // *** End programmer edit section *** (СотрудникиКу.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СотрудникиКу.Код Set start)

                // *** End programmer edit section *** (СотрудникиКу.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (СотрудникиКу.Код Set end)

                // *** End programmer edit section *** (СотрудникиКу.Код Set end)
            }
        }
        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СотрудникиКу.Фио CustomAttributes)

        // *** End programmer edit section *** (СотрудникиКу.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СотрудникиКу.Фио Get start)

                // *** End programmer edit section *** (СотрудникиКу.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СотрудникиКу.Фио Get end)

                // *** End programmer edit section *** (СотрудникиКу.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СотрудникиКу.Фио Set start)

                // *** End programmer edit section *** (СотрудникиКу.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СотрудникиКу.Фио Set end)

                // *** End programmer edit section *** (СотрудникиКу.Фио Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники ку.
        /// </summary>
        // *** Start programmer edit section *** (СотрудникиКу.Должности CustomAttributes)

        // *** End programmer edit section *** (СотрудникиКу.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.VUA.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (СотрудникиКу.Должности Get start)

                // *** End programmer edit section *** (СотрудникиКу.Должности Get start)
                IIS.VUA.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (СотрудникиКу.Должности Get end)

                // *** End programmer edit section *** (СотрудникиКу.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СотрудникиКу.Должности Set start)

                // *** End programmer edit section *** (СотрудникиКу.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (СотрудникиКу.Должности Set end)

                // *** End programmer edit section *** (СотрудникиКу.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиКуE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиКуE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиКуE", typeof(IIS.VUA.СотрудникиКу));
                }
            }
            
            /// <summary>
            /// "СотрудникиКуL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиКуL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиКуL", typeof(IIS.VUA.СотрудникиКу));
                }
            }
        }
    }
}
