//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип.
    /// </summary>
    // *** Start programmer edit section *** (Тип CustomAttributes)

    // *** End programmer edit section *** (Тип CustomAttributes)
    public enum Тип
    {
        
        // *** Start programmer edit section *** (Тип.Начислено CustomAttributes)

        // *** End programmer edit section *** (Тип.Начислено CustomAttributes)
        [Caption("Начислено")]
        Начислено,
        
        // *** Start programmer edit section *** (Тип.Удержано CustomAttributes)

        // *** End programmer edit section *** (Тип.Удержано CustomAttributes)
        [Caption("Удержано")]
        Удержано,
    }
}
